"""Add countdown_enabled to users

Revision ID: 0a724279e3ff
Revises: 265eacb7cd85
Create Date: 2026-02-25 17:32:00.498163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a724279e3ff'
down_revision = '265eacb7cd85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('countdown_enabled', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('countdown_enabled')

    # ### end Alembic commands ###
