"""Initial migration — capture existing schema

Revision ID: 265eacb7cd85
Revises: 
Create Date: 2026-02-25 16:29:21.000550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '265eacb7cd85'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('beer_posts', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.create_index(batch_op.f('ix_beer_posts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_beer_posts_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('beer_posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_beer_posts_user_id'))
        batch_op.drop_index(batch_op.f('ix_beer_posts_created_at'))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    # ### end Alembic commands ###
