"""Add composite index on comments

Revision ID: 4017e54db22a
Revises: 97ead9d80e34
Create Date: 2026-02-27 23:14:27.745328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4017e54db22a'
down_revision = '97ead9d80e34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.create_index('idx_comment_post_created', ['post_id', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_index('idx_comment_post_created')

    # ### end Alembic commands ###
