"""add hide_own_posts to user

Revision ID: 97ead9d80e34
Revises: 0a724279e3ff
Create Date: 2026-02-27 14:21:52.162724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97ead9d80e34'
down_revision = '0a724279e3ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hide_own_posts', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('hide_own_posts')

    # ### end Alembic commands ###
